### PR TITLE
Update residual_blocks.py

### PR DESCRIPTION
**Pull request by vangorik**
py3 compatible

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Oh, I always forget. Thanks.

**Comment by keunwoochoi** [comment]
@vangorik, the current implementation doesn't seem to working properly. Do you have any idea on it?
There are some ambiguities on the paper, but looks like the block itself is correctly implemented. Still the example doesn't make any progress.

**Comment by vangorik** [comment]
look this code: https://github.com/Sebubu/mushroom_crawler/blob/master/mushroom/ResidualNet.py
It seems to be cleaner written

**Comment by keunwoochoi** [comment]
Looks neat, thanks!

**Pull request merged**
